name: Arduino Build
on:
  push:
    branches: [ 'master' ]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Npm install
        run: npm install
      - name: Run build script
        run: ./build_progmem.sh
      - name: Compile Sketch
        uses: arduino/compile-sketches@v1.1.0
        with:
          platforms: |
            - name: "m5stack:esp32"
              source-url: https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json
          fqbn: m5stack:esp32:m5stack_stickc_plus2
          sketch-paths: |
            - OTPAuth-M5StickC
          libraries: |
            - name: Arduinojson
            - name: M5GFX
            - name: M5Unified
            - name: TOTP library
            - name: Time
